apiVersion: apps/v1
kind: Deployment
metadata:
  name: breweryprx-deploy
spec:
  selector:
    matchLabels:
      app: breweryprx
  replicas: 3
  template:
    metadata:
      labels:
        app: breweryprx
    spec:
      containers:
        - name: breweryprx
          image: 'hectormao/breweryprx:0.0.2'
---
apiVersion: v1
kind: Service
metadata:
  name: breweryprx-service
spec:
  type: NodePort
  selector:
    app: breweryprx
  ports:
    - protocol: TCP
      port: 3000
      nodePort:
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: breweryprx-ingress
spec:
  rules:
    - host: breweryprx.info
      http:
        paths:
          - path: /brewery
            pathType: Exact
            backend:
              service:
                name: breweryprx-service
                port:
                  number: 3000
